version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: data from greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        description: product table of greenweez 
      - name: sales
        identifier: raw_gz_sales
        description: sales table of greenweez / we have one row per products_id found in each orders_id.
      - name: ship
        identifier: raw_gz_ship
        description: shipping table of greenweez 
models: 
  - name: ship
    description: Shipping table of greenweez
    columns: 
      - name: orders_id
        description: Primary key of the table
        tests:
          - unique:
          - not_null:
  - name: product
    description: Product table of greenweez
    columns: 
      - name: products_id
        description: Primary key of the table
        tests:
          - unique:
          - not_null: