version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: data from greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        description: product table of greenweez 
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the purchase price of the product
      - name: sales
        identifier: raw_gz_sales
        description: sales table of greenweez / we have one row per products_id found in each orders_id.
        columns:
          - name: date_date
            description: the date of purchace
          - name: orders_id
            description: foreing key to ship
          - name: pdt_id
            description: foreing key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = qunatity * selling_price
          - name: quantity
            description: the quantity of the products purchased for this order
        tests:
            - unique:            
                column_name: "(orders_id || '-' || pdt_id)"
            ##OR## 
            - dbt_utils.unique_combination_of_columns:
                combination_of_columns: 
                  - orders_id
                  - pdt_id
      - name: ship
        identifier: raw_gz_ship
        description: shipping table of greenweez 
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the warehouse
          - name: ship_cost
            description: the shipping cost paid by Greenweez to the carrier/ transporter